global: &global
  adapter: postgresql
  pool: 5
  timeout: 5000
  min_messages: warning
  encoding: utf8

development:
  database: Hold_development
  <<: *global

test: &test
  database: Hold_test<%=ENV['TEST_ENV_NUMBER']%>
  <<: *global

production:
  database: Hold_production
  <<: *global
